# Generated by Django 5.2 on 2025-04-11 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atributos', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atributos.atributo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('atributo', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='atributo',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='atributos', through='atributos.ProductoAtributo', to='products.product'),
        ),
    ]
