# Generated by Django 5.2 on 2025-04-11 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notaventas', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notaventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notaventas.notaventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('notaventa', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='notaventa',
            name='notaventas',
            field=models.ManyToManyField(blank=True, related_name='notaventas', through='notaventas.DetalleVenta', to='products.product'),
        ),
    ]
