# Generated by Django 5.2 on 2025-04-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPLEADO', 'Empleado'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10),
        ),
    ]
